# -*- conf -*-

term=foot
font=gallant12x22:size=12,FantasqueSansM Nerd Font Mono:size=11,Noto Sans Mono:size=11,Noto Color Emoji:size=11
dpi-aware=yes
initial-color-theme=light
pad=8x6
resize-by-cells=yes
bold-text-in-bright=no
box-drawings-uses-font-glyphs=yes
gamma-correct-blending=no

[scrollback]
lines=10000

[cursor]
style=block
blink=no

[colors-dark]
alpha=1.0
background=ffffff
foreground=000000
regular0=000000
regular1=990000
regular2=006600
regular3=996600
regular4=003f8c
regular5=7a287a
regular6=007070
regular7=b0b0b0
bright0=555555
bright1=cc0000
bright2=008800
bright3=aa7700
bright4=0057b8
bright5=9b3a9b
bright6=008f8f
bright7=ffffff

[colors-light]
alpha=1.0
background=ffffff
foreground=000000
regular0=000000
regular1=990000
regular2=006600
regular3=996600
regular4=003f8c
regular5=7a287a
regular6=007070
regular7=b0b0b0
bright0=555555
bright1=cc0000
bright2=008800
bright3=aa7700
bright4=0057b8
bright5=9b3a9b
bright6=008f8f
bright7=ffffff

[csd]
preferred=none
